version: '3.2'
services:
      mydb:
        image: postgres
        mem_limit: 2048MB
        mem_reservation: 1G
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        volumes:
          - db-data:/var/lib/postgres/data
        ports:
          - "5432:5432"
        networks:
          - exchange-network
networks:
  exchange-network:
    driver: bridge

volumes:
  db-data:

